### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by Corantin** [1Hive/quests#256]
- [x] Implement JSON-RPC for gnosis
- [x] Deploy contracts (QuestFactory and Quest + Govern + GovernQueue) on Gnosis
- [x] Deploy subgraphs (Govern, Quests) on Gnosis
- [x] Create a stagging branch
- [x] Register and configure Quests subdomain quests.1hive.org
- [x] Configure Vercel to CD in main branch and staging
- [x] Create a gnosis-safe on gnosis chain for managing admin operation

**Comment by kamikazebr** [comment]
> * Deploy the webapp to IPFS

What it means? So we dont pretend use Vercel to deploy?

**Comment by Corantin** [comment]
Oh maybe I dont know I thought that IPFS was the way to go for web3
projects but actually might me simpler for continuous deployment if we can
stick to vercel but with another domain than quests.vercel.app

**Comment by kamikazebr** [comment]
I like idea IPFS hosting, maybe just need create some GitHub action to CD
on that.

I just don't know about the stability on that.

Em seg., 2 de mai. de 2022 23:38, Corantin ***@***.***>
escreveu:

> Oh maybe I dont know I thought that IPFS was the way to go for web3
> projects but actually might me simpler for continuous deployment if we can
> stick to vercel but with another domain than quests.vercel.app
>
> On Mon., May 2, 2022, 9:08 p.m. Felipe Novaes F Rocha, <

**Comment by Corantin** [comment]
In fact we already have that script in WebApp package

**Comment by kamikazebr** [comment]
We are starting using fleek.co in Gardens with eth.limo domain, looks good option to decentralized hosting.
